#include <cstring>

using namespace std;

#include "asmparser.h"
#include "utils.h"

ASMParser::ASMParser(CPU * cpu0, const char * fname)
{
	cpu = cpu0; fp = 0; asm_name = fname;
}

ASMParser::~ASMParser()
{
	if (fp) fclose(fp);
}

int ASMParser::Open()
{
	if (strcmp(asm_name + strlen(asm_name) - 4, ".asm") != 0)
	{
		printf("Incorrect ASM file extension : %s\n", asm_name); return -1;
	}
	fp = fopen(asm_name, "r");
	if (fp == 0)
	{
		printf("Cannot open (%s)\n", asm_name); return -1;
	}
	///	1st pass : extract labels
	if (Parse(1) != 0)
	{
		return -1;
	}
	EMIT_MESSAGE_0(cpu->PrintSeparator, cpu->fplog);
	EMIT_MESSAGE_0(cpu->label.PrintLabels, cpu->fplog);
	rewind(fp);
	///	2nd pass : extract instructions
	if (Parse(2) != 0)
	{
		return -1;
	}
	EMIT_MESSAGE_0(cpu->PrintSeparator, cpu->fplog);
	EMIT_MESSAGE_1(cpu->PrintMemory, cpu->fplog, CPU::PM_Program);
	EMIT_MESSAGE_0(cpu->PrintSeparator, cpu->fplog);
	fclose(fp);
	fp = 0;
	if (WriteVerilogMemFile() != 0 || WriteVerilogMonitorFile() != 0)
	{
		return -1;
	}
	return 0;
}

void ASMParser::Close()
{
	if (fp)
	{
		fclose(fp);
	}
	fp = 0;
	WriteVerilogMemProbeFile();
}

FILE * ASMParser::OpenFile(const char *extname)
{
	FILE * fp0 = 0;
	char * mem_fname = new char[strlen(asm_name) + strlen(VERILOG_DIR) + strlen(extname) + 1];
	sprintf(mem_fname, "%s%s", VERILOG_DIR, asm_name);
	char * p = mem_fname + strlen(mem_fname) - 4;
	if (*p != '.')
	{
		printf("sorry, something is wrong... (please contact admin)\n");
	}
	else
	{
		strcpy(p, extname); fp0 = fopen(mem_fname, "w");
	}
	delete[] mem_fname;
	return fp0;
}

int ASMParser::WriteVerilogMemFile()
{
	FILE * fp0 = OpenFile(".mem");
	if (fp0)
	{
		fprintf(fp0, "/// Verilog Memory Initialization File (.mem) generated by %s\n\n"
			"/// 12-bit address\n"
			"/// 16-bit data\n\n"
			, tool_name);
		cpu->PrintMemory(fp0, CPU::PM_Verilog | CPU::PM_Program);
		fclose(fp0);
		return 0;
	}
	else
	{
		printf("Cannot open memory output file (skipped memory output)\n"); return -1;
	}
}

int ASMParser::WriteVerilogMemProbeFile()
{
	FILE * fp0 = OpenFile(".prb");
	if (fp0)
	{
		fprintf(fp0, "/// Verilog Memory Probe File (.prb) generated by %s\n\n"
			"/// bit[31:28] : memory type (0000 : data, 1111 : end-of-memory\n"
			"/// bit[27:16] : address\n"
			"/// bit[15:0]  : data\n\n"
			, tool_name);
		cpu->PrintMemory(fp0, CPU::PM_Verilog);
		fprintf(fp0, "%1x%03x%04x\t///\t%s\n", 0xf, 0, 0, "end-of-memory");
		fclose(fp0);
		return 0;
	}
	else
	{
		printf("Cannot open memory output file (skipped memory output)\n"); return -1;
	}
}

int ASMParser::WriteVerilogMonitorFile()
{
	FILE * fp0 = OpenFile(".mon");
	if (fp0)
	{
		fprintf(fp0, "/// Verilog Monitor File (.mon) generated by %s\n\n"
			"/// bit[31:28] : memory type (0000 : prog, 0001 : data, 1111 : end-of-memory\n"
			"/// bit[27:16] : address\n"
			"/// bit[15:0]  : data\n\n"
			, tool_name);
		cpu->PrintMemory(fp0, CPU::PM_Verilog | CPU::PM_Monitor);
		fprintf(fp0, "%08x\t///\t%s\n", (unsigned int)(-1), "end-of-memory");
		fclose(fp0);
		return 0;
	}
	else
	{
		printf("Cannot open memory output file (skipped memory output)\n"); return -1;
	}
}

void ASMParser::SkipWhiteSpace(const char ** pp)
{
	const char * p = *pp;
	while (*p == ' ' || *p == '\t')
	{
		p++;
	}
	*pp = p;
}

int ASMParser::GetNum(const char ** pp, int insnType)
{
	if (insnType == InsnSet::I_CHR)
	{
		return **pp;
	}
	const char * p = *pp;
	int val = 0;
	int first = 1;
	int base = 0;
	switch (insnType)
	{
	case InsnSet::I_ORG:
	case InsnSet::I_HEX:	base = 16;	break;
	case InsnSet::I_DEC:	base = 10;	break;
	default:				return -1;
	}
	int sign = 0;
	if (*p == '-')
	{
		sign = 1; p++;
	}
	while (*p)
	{
		if (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r' || *p == COMMENT)
		{
			break;
		}
		val *= base;
		int num = *p - '0';
		if (num >= 0 && num <= 9)
		{
			val += num;
		}
		else if (base == 16)
		{
			int upper = *p - 'A';
			int lower = *p - 'a';
			if (upper >= 0 && upper <= 5)
			{
				val += upper + 10;
			}
			else if (lower >= 0 && lower <= 5)
			{
				val += lower + 10;
			}
			else
			{
				return -1;
			}	///	error
		}
		else
		{
			return -1;
		}	/// error
		p++;
		first = 0;
	}
	*pp = p;
	if (sign)
	{
		val = -val;
	}
	return (first) ? -1 : val;
}

int ASMParser::GetLabelLength(const char * p)
{
	int nlen = 0;
	while (*p)
	{
		switch (*p)
		{
		case ' ':
		case '\r':
		case '\t':
		case '\n':
		case ',':	return nlen;
		default:	break;
		}
		nlen++;
		p++;
	}
	return 0;
}

int ASMParser::ExtractComment(const char * p, int addr, int headFlag)
{
	if (addr >= 0 && addr < cpu->mem->size)
	{
		Memory::Word * m = &cpu->mem->word[addr];
		SkipWhiteSpace(&p);
		if (*p == '/')
		{
			const char * pp = p;
			while (*pp && *pp != '\r' && *pp != '\n')
			{
				pp++;
			}
			m->SetComment(p, pp - p, headFlag);
			return 1;
		}
	}
	return 0;
}
void ASMParser::PrintErrorLocation()
{
	printf("Error occurred on line %d\n", asmLineNum);
}

int ASMParser::ParseLabel(const char * p)
{
	int nlen = 0;
	while (*p)
	{
		switch (*p)
		{
		case ' ':
		case '\t':	return 0;
		case ',':	return nlen;
		default:	break;
		}
		nlen++;
		p++;
	}
	return 0;
}

int ASMParser::ParseLabel(int passNum, const char ** p, int & addr)
{
	if (passNum == 2 && ExtractComment(*p, addr, 1))
	{
		return 1;
	}
	SkipWhiteSpace(p);
	if (**p == '/')
	{
		return 1;
	}	///	comment...
	int labelLength = ParseLabel(*p);
	if (labelLength > 0)
	{
		if (cpu->label.annotation.AddAnnotation(*p, labelLength, (unsigned short)addr))
		{
		}
		else if (passNum == 1)
		{	///	create label
			if (cpu->label.AddLabel(*p, labelLength, (unsigned short)addr) == 0)
			{
				PrintErrorLocation(); return -1;
			}
		}
		else if (cpu->label.GetLabel(*p, labelLength) == 0)
		{
			printf("ERROR: label(%s) not found in 1st pass (bug in the parser...)\n", p); PrintErrorLocation(); return -1;
		}
		*p += labelLength + 1;
		SkipWhiteSpace(p);
		if (passNum == 2)
		{
			ExtractComment(*p, addr, 1);
		}
		if (**p == '/')
		{
			return 1;
		}
	}
	return (**p == '\n' || **p == '\r') ? 1 : 0;
}

int ASMParser::ParseNonInsn(int passNum, const char * p, int insnID, int & addr)
{
	SkipWhiteSpace(&p);
	int param = GetNum(&p, insnID);
	Memory::Word * m = &cpu->mem->word[addr];
	int endReached = 0;
	switch (insnID)
	{
	case InsnSet::I_ORG:
		addr = param;
		if (!cpu->mem->IsValidAddress(addr))
		{
			printf("ERROR: ORG has invalid address %d (0x%x)\n", addr, addr); PrintErrorLocation(); return -1;
		}
		if (passNum == 2)
		{
			ExtractComment(p, addr, 1);
		}
		break;
	case InsnSet::I_END:
		endReached = 1;
		break;
	case InsnSet::I_SYM:
		if (passNum == 2)
		{
			SkipWhiteSpace(&p);
			int len = GetLabelLength(p);
			if (len == 0)
			{
				printf("ERROR: label(%s) length = 0 (bug in parser)\n", p); PrintErrorLocation(); return -1;
			}
			Label::Element * lb = cpu->label.GetLabel(p, len);
			if (lb == 0)
			{
				printf("ERROR: label(%s) not found in the 1st pass (bug in the program...)\n", p); PrintErrorLocation(); return -1;
			}
			if (!cpu->mem->IsValidAddress(lb->address))
			{
				printf("ERROR: label(%s) has invalid address (%x)\n", lb->name, lb->address); PrintErrorLocation(); return -1;
			}
			param = lb->address;
		}
	case InsnSet::I_CHR:
	case InsnSet::I_HEX:
	case InsnSet::I_DEC:
		if (passNum == 2)
		{
			m->SetStatus(&cpu->label.annotation, addr);
			cpu->dbg->InsertMonitorOrBreakpoint(m->status, addr, false);
			m->value = param;
		}
		if (passNum == 2)
		{
			ExtractComment(p, addr, 0);
		}
		addr++;
		break;
	default:
		break;
	}
	return (endReached) ? 1 : 0;
}

int ASMParser::ParseBlockCommentStart(const char ** p)
{
	if (!blockCommentPending)
	{
		SkipWhiteSpace(p);
		if (strncmp(*p, "/*", 2) == 0)
		{
			blockCommentPending = 1; (*p) += 2; return 1;
		}
	}
	return 0;
}

int ASMParser::ParseBlockCommentEnd(const char ** p)
{
	if (blockCommentPending)
	{
		while (**p)
		{
			if (strncmp(*p, "*/", 2) == 0)
			{
				(*p) += 2; blockCommentPending = 0; return 1;
			}
			else
			{
				(*p)++;
			}
		}
	}
	return 0;
}

int ASMParser::ParseBlockComment(const char ** p)
{
	while (ParseBlockCommentStart(p) || ParseBlockCommentEnd(p))
	{
	}
	return (blockCommentPending != 0);
}

int ASMParser::Parse(int passNum)
{
	if (passNum != 1 && passNum != 2)
	{
		printf("passNum = %d is invalid\n", passNum); return -1;
	}
	char buf[MAX_LINE];
	int addr = 0, endReached = 0;
	blockCommentPending = 0;
	asmLineNum = 0;
	while (!endReached)
	{
		if (fgets(buf, MAX_LINE, fp) == 0)
		{
			printf("ERROR: End of file reached before END\n"); return -1;
		}
		asmLineNum++;
		const char * p = buf;
		if (ParseBlockComment(&p))
		{
			continue;
		}
		switch (ParseLabel(passNum, &p, addr))
		{
		case -1:	return -1;
		case  1:	continue;
		default:	break;
		}
		InsnSet::Insn * insn = cpu->isa->SearchInsn(&p);
		if (insn == 0)
		{
			printf("ERROR: Invalid instruction (%s)\n", p); PrintErrorLocation(); return -1;
		}
		switch (ParseInsn(passNum, p, insn, addr))
		{
		case -1:	return -1;
		case  1:	continue;
		default:	break;
		}
		switch (ParseNonInsn(passNum, p, insn->ID, addr))
		{
		case -1:	return -1;
		case  1:	endReached = 1;
		default:	break;
		}
	}
	if (passNum == 1)
	{
		if (!cpu->mem->IsValidAddress(addr))
		{
			printf("ERROR: program extends to invalid address %d (0x%x)\n", addr, addr); return -1;
		}
		cpu->mem->maxAddr = addr;
	}
	return 0;
}
