#include "asmparser.h"

ASMParser::ASMParser(const std::shared_ptr<CPU>& cpu0, const std::string fname)
		: asm_name(fname)
{
    cpu = cpu0;
}

ASMParser::~ASMParser()
{
}

int ASMParser::Open()
{
    if (asm_name.substr((asm_name.size()-4)) != ".asm")
	{
		printf("Incorrect ASM file extension : %s\n", asm_name.c_str());
        return -1;
	}
	fp.reset(fopen(asm_name.c_str(), "r"), fclose);
	if (!fp)
	{
		printf("Cannot open (%s)\n", asm_name.c_str());
        return -1;
	}
	///	1st pass : extract labels
	if (Parse(1) != 0)
	{
		return -1;
	}
	EMIT_MESSAGE_0(cpu->PrintSeparator, cpu->fplog.get());
	EMIT_MESSAGE_0(cpu->label.PrintLabels, cpu->fplog.get());
	rewind(fp.get());
	///	2nd pass : extract instructions
	if (Parse(2) != 0)
	{
		return -1;
	}
	EMIT_MESSAGE_0(cpu->PrintSeparator, cpu->fplog.get());
	EMIT_MESSAGE_1(cpu->PrintMemory, cpu->fplog.get(), CPU::PM_Program);
	EMIT_MESSAGE_0(cpu->PrintSeparator, cpu->fplog.get());
	if (WriteVerilogMemFile() != 0 || WriteVerilogMonitorFile() != 0)
	{
		return -1;
	}
	return 0;
}

void ASMParser::Close()
{
	WriteVerilogMemProbeFile();
}

std::shared_ptr<FILE> ASMParser::OpenFile(const std::string& extname)
{
	std::string mem_fname = VERILOG_DIR + asm_name;
	if (mem_fname[mem_fname.size()-4] != '.')
	{
		printf("sorry, something is wrong... (please contact admin)\n");
        return std::shared_ptr<FILE>(nullptr);
	}
	else
	{
        mem_fname  = mem_fname.substr(0,mem_fname.size()-4) + extname;
        return std::shared_ptr<FILE>(fopen(mem_fname.c_str(), "w"),fclose);
	}
}

int ASMParser::WriteVerilogMemFile()
{
	std::shared_ptr<FILE> fp0 = OpenFile(".mem");
	if (fp0)
	{
		fprintf(fp0.get(), "/// Verilog Memory Initialization File (.mem) generated by %s\n\n"
			"/// 12-bit address\n"
			"/// 16-bit data\n\n"
			, tool_name.c_str());
		cpu->PrintMemory(fp0.get(), CPU::PM_Verilog | CPU::PM_Program);
		return 0;
	}
	else
	{
		printf("Cannot open memory output file (skipped memory output)\n");
        return -1;
	}
}

int ASMParser::WriteVerilogMemProbeFile()
{
	std::shared_ptr<FILE> fp0 = OpenFile(".prb");
	if (fp0)
	{
		fprintf(fp0.get(), "/// Verilog Memory Probe File (.prb) generated by %s\n\n"
			"/// bit[31:28] : memory type (0000 : data, 1111 : end-of-memory\n"
			"/// bit[27:16] : address\n"
			"/// bit[15:0]  : data\n\n"
			, tool_name.c_str());
		cpu->PrintMemory(fp0.get(), CPU::PM_Verilog);
		fprintf(fp0.get(), "%1x%03x%04x\t///\t%s\n", 0xf, 0, 0, "end-of-memory");
		return 0;
	}
	else
	{
		printf("Cannot open memory output file (skipped memory output)\n");
		return -1;
	}
}

int ASMParser::WriteVerilogMonitorFile()
{
	std::shared_ptr<FILE> fp0 = OpenFile(".mon");
	if (fp0)
	{
		fprintf(fp0.get(), "/// Verilog Monitor File (.mon) generated by %s\n\n"
			"/// bit[31:28] : memory type (0000 : prog, 0001 : data, 1111 : end-of-memory\n"
			"/// bit[27:16] : address\n"
			"/// bit[15:0]  : data\n\n"
			, tool_name.c_str());
		cpu->PrintMemory(fp0.get(), CPU::PM_Verilog | CPU::PM_Monitor);
		fprintf(fp0.get(), "%08x\t///\t%s\n", (unsigned int)(-1), "end-of-memory");
		return 0;
	}
	else
	{
		printf("Cannot open memory output file (skipped memory output)\n");
		return -1;
	}
}

void ASMParser::SkipWhiteSpace(std::string& pp)
{
    while(pp.find_first_of(" 　\t") == 0)
    {
        pp.erase(pp.begin());
        if(pp.empty()) break;
    }
}

int ASMParser::GetNum(std::string& pp, int insnType)
{
	if (insnType == InsnSet::I_CHR)
	{
		return pp.front();
	}
	int val = 0;
	int first = 1;
	int base = 0;
	switch (insnType)
	{
        case InsnSet::I_ORG:
        case InsnSet::I_HEX:	base = 16;	break;
        case InsnSet::I_DEC:	base = 10;	break;
        default:				return -1;
	}
	int sign = 0;
	if (pp.front() == '-')
	{
		sign = 1;
        pp.erase(pp.begin());
	}
	while (pp.front())
	{
        char p = pp.front();
		if (p == ' ' || p == '\t' || p == '\n' || p == '\r' || p == COMMENT)
		{
			break;
		}
		val *= base;
		int num = p - '0';
		if (num >= 0 && num <= 9)
		{
			val += num;
		}
		else if (base == 16)
		{
			int upper = p - 'A';
			int lower = p - 'a';
			if (upper >= 0 && upper <= 5)
			{
				val += upper + 10;
			}
			else if (lower >= 0 && lower <= 5)
			{
				val += lower + 10;
			}
			else
			{
				return -1;
			}	///	error
		}
		else
		{
			return -1;
		}	/// error
		pp.erase(pp.begin());
		first = 0;
	}
	if (sign)
	{
		val = -val;
	}
	return (first) ? -1 : val;
}

int ASMParser::GetLabelLength(const std::string& p)
{
	int nlen = 0;
	while (p[nlen])
	{
		switch (p[nlen])
		{
            case ' ':
            case '\r':
            case '\t':
            case '\n':
            case ',':	return nlen;
            default:	break;
		}
		++nlen;
	}
	return 0;
}

int ASMParser::ExtractComment(std::string& p, int addr, int headFlag)
{
	if (addr >= 0 && addr < cpu->mem->size)
	{
		SkipWhiteSpace(p);
		if (p.front() == '/')
		{
            int len = 0;
			while (p[len] && p[len] != '\r' && p[len] != '\n')
			{
                ++len;
			}
			cpu->mem->word[addr].SetComment(p, len, headFlag);
            return 1;
		}
	}
	return 0;
}

void ASMParser::PrintErrorLocation()
{
	printf("Error occurred on line %d\n", asmLineNum);
}

int ASMParser::ParseLabel(const std::string& p)
{
	int nlen = 0;
	while (p[nlen])
	{
		switch (p[nlen])
		{
            case ' ':
            case '\t':	return 0;
            case ',':	return nlen;
            default:	break;
		}
		++nlen;
	}
	return 0;
}

int ASMParser::ParseLabel(int passNum, std::string& p, int addr)
{
	if (passNum == 2 && ExtractComment(p, addr, 1))
	{
		return 1;
	}
	SkipWhiteSpace(p);
	if (p.front() == '/')
	{
		return 1;
	}	///	comment...
	int labelLength = ParseLabel(p);
	if (labelLength > 0)
	{
		if (cpu->label.annotation.AddAnnotation(p, labelLength, (unsigned short)addr))
		{
		}
		else if (passNum == 1)
		{	///	create label

			if ((cpu->label.AddLabel(p, labelLength, (unsigned short)addr)).name.empty())
			{
				PrintErrorLocation();
				return -1;
			}
		}
		else if ((cpu->label.GetLabel(p, labelLength)).name.empty())
		{
			printf("ERROR: label(%s) not found in 1st pass (bug in the parser...)\n", p.c_str());
            PrintErrorLocation();
            return -1;
		}
        p.erase(0, labelLength+1);
		SkipWhiteSpace(p);
		if (passNum == 2)
		{
			ExtractComment(p, addr, 1);
		}
		if (p.front() == '/')
		{
			return 1;
		}
	}
	return (p.front() == '\n' || p.front() == '\r') ? 1 : 0;
}

int ASMParser::ParseNonInsn(int passNum, std::string& p, int insnID, int& addr)
{
	SkipWhiteSpace(p);
	int param = GetNum(p, insnID);
    int endReached = 0;
	switch (insnID)
	{
        case InsnSet::I_ORG:
            addr = param;
            if (!cpu->mem->IsValidAddress(addr))
            {
                printf("ERROR: ORG has invalid address %d (0x%x)\n", addr, addr);
                PrintErrorLocation();
                return -1;
            }
            if (passNum == 2)
            {
                ExtractComment(p, addr, 1);
            }
            break;
        case InsnSet::I_END:
            endReached = 1;
            break;
        case InsnSet::I_SYM:
            if (passNum == 2)
            {
                SkipWhiteSpace(p);
                int len = GetLabelLength(p);
                if (len == 0)
                {
                    printf("ERROR: label(%s) length = 0 (bug in parser)\n", p.c_str());
                    PrintErrorLocation();
                    return -1;
                }
                Label::Element lb = cpu->label.GetLabel(p, len);
                if (lb.name.empty())
                {
                    printf("ERROR: label(%s) not found in the 1st pass (bug in the program...)\n", p.c_str());
                    PrintErrorLocation();
                    return -1;
                }
                if (!cpu->mem->IsValidAddress(lb.address))
                {
                    printf("ERROR: label(%s) has invalid address (%x)\n", lb.name.c_str(), lb.address);
                    PrintErrorLocation();
                    return -1;
                }
                param = lb.address;
            }
        case InsnSet::I_CHR:
        case InsnSet::I_HEX:
        case InsnSet::I_DEC:
            if (passNum == 2)
            {
                cpu->mem->word[addr].SetStatus(cpu->label.annotation, addr);
                cpu->dbg->InsertMonitorOrBreakpoint(cpu->mem->word[addr].status, addr, false);
                cpu->mem->word[addr].value = param;
            }
            if (passNum == 2)
            {
                ExtractComment(p, addr, 0);
            }
            ++addr;
            break;
        default:
            break;
	}
	return (endReached) ? 1 : 0;
}

int ASMParser::ParseBlockCommentStart(std::string& p)
{
	if (!blockCommentPending)
	{
		SkipWhiteSpace(p);
        if (p.substr(0,2) == "/*")
		{
			blockCommentPending = 1;
            p.erase(0,2);
            return 1;
		}
	}
	return 0;
}

int ASMParser::ParseBlockCommentEnd(std::string& p)
{
	if (blockCommentPending)
	{
		while (p.front())
		{
            if (p.substr(0,2) == "*/")
			{
                p.erase(0,2);
                blockCommentPending = 0;
				return 1;
			}
			else
			{
                p.erase(p.begin());
			}
		}
	}
	return 0;
}

int ASMParser::ParseBlockComment(std::string& p)
{
	while (ParseBlockCommentStart(p) || ParseBlockCommentEnd(p))
	{
	}
	return (blockCommentPending != 0);
}

int ASMParser::Parse(int passNum)
{
	if (passNum != 1 && passNum != 2)
	{
		printf("passNum = %d is invalid\n", passNum);
        return -1;
	}
	char buf[MAX_LINE];
    std::string p;
	int addr = 0, endReached = 0;
	blockCommentPending = 0;
	asmLineNum = 0;
	while (!endReached)
	{
        if (fgets(buf, MAX_LINE, fp.get()) == 0)
		{
			printf("ERROR: End of file reached before END\n");
            return -1;
		}
		++asmLineNum;
		p = buf;
		if (ParseBlockComment(p))
		{
			continue;
		}
		switch (ParseLabel(passNum, p, addr))
		{
            case -1:	return -1;
            case  1:	continue;
            default:	break;
		}
		InsnSet::Insn insn = cpu->isa->SearchInsn(p);
		if (insn.ID == 0)
		{
			printf("ERROR: Invalid instruction (%s)\n", p.c_str());
            PrintErrorLocation();
            return -1;
		}
		switch (ParseInsn(passNum, p, insn, addr))
		{
            case -1:	return -1;
            case  1:	++addr; continue;
            default:	break;
		}
		switch (ParseNonInsn(passNum, p, insn.ID, addr))
		{
            case -1:	return -1;
            case  1:	endReached = 1;
            default:	break;
		}
	}
	if (passNum == 1)
	{
		if (!cpu->mem->IsValidAddress(addr))
		{
			printf("ERROR: program extends to invalid address %d (0x%x)\n", addr, addr);
			return -1;
		}
		cpu->mem->maxAddr = addr;
	}
	return 0;
}
